baseURL = "https://lightwindow.github.io/"
languageCode = 'en-us'
title = 'lightwindow'
theme = 'archie'

paginate = 10 # articles per page

[params]
mode = "dark" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = '''
stuff about programming \
\
Credits \
Made with: [Hugo](https://gohugo.io) \
Hugo theme: [Archie](https://github.com/athul/archie)
'''
mathjax = true # enable MathJax support
katex = true # enable KaTeX support
customcss = ["css/custom.css"]
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lightwindow"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/lightwindow"

# Main menu Items

# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
